# Generated by Django 6.0.6 on 2026-06-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
