# Generated by Django 6.0.6 on 2026-07-26 08:25

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='total_days',
        ),
        migrations.AddField(
            model_name='leave',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 7, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Sick', 'Sick'), ('Earned', 'Earned'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity'), ('Other', 'Other')], default=datetime.date(2026, 7, 26), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='reason',
            field=models.TextField(default='Casual'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejevted', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
